# Generated by Django 4.0.3 on 2022-03-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=4807425737),
            preserve_default=False,
        ),
    ]
